all:
  vars:
    ansible_user: root
  hosts:
    debian_master: 
      ansible_host: 192.168.1.137 # enter your target server address
  children:
    debian_hosts:
      hosts:
        debian_master:
